import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'index',
    {
      type: 'category',
      label: '指南',
      items: [
        'guide/how-to-use-this-site',
        'guide/exam-strategy',
      ],
    },
    {
      type: 'category',
      label: '科目',
      items: [
        {
          type: 'autogenerated',
          dirName: 'subjects',
        },
      ],
    },
  ],
};

export default sidebars;
